### ISSUE TITLE
'NYSE' is the New York Stock Exchange， not XNYS

### ISSUE THREAD

**Issue by xinmans** [LukeWang01/TradingBot_MooMoo#2]
Wall-TradingBot-MooMoo/utils/time_tool.py
   ```
 # Specify the market calendar (e.g., 'NYSE' for New York Stock Exchange)
    nyse = mcal.get_calendar('NYSE')
   ```

**Comment by LukeWang01** [comment]
> Wall-TradingBot-MooMoo/utils/time_tool.py
> 
> ```
> # Specify the market calendar (e.g., 'NYSE' for New York Stock Exchange)
>  nyse = mcal.get_calendar('NYSE')
> ```

`nyse = mcal.get_calendar('NYSE')` is the correct usage.

1. NYSE
Description: Refers to the New York Stock Exchange (NYSE) calendar. It is one of the more commonly used calendars in pandas-market-calendars.

Typical Usage: It includes trading days for the NYSE but may not align perfectly with some other identifiers like XNYS, which are based on international standards.

2. XNYS
Description: Refers to the MIC (Market Identifier Code) for the NYSE, which is XNYS.

The MIC is a globally standardized code assigned by the International Organization for Standardization (ISO) to financial market infrastructures.
Using MIC codes like XNYS ensures alignment with globally recognized market identifiers.

please refer below:
https://www.tradinghours.com/mic/s/xnys
